# Generated by cucumber-sinatra. (2015-03-31 20:20:58 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/battleships.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Battleships

class BattleshipsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BattleshipsWorld.new
end

Before('@ships_placed') do
  visit '/'
  fill_in('place_ship_1', with: 'A1')
  fill_in('place_ship_2', with: 'B1')
  fill_in('place_ship_3', with: 'C1')
  click_button('place')
end

Before('@ship_missed') do
  fill_in('to_fire_at', with: 'A2')
  click_button('fire')
end
